<#
.SYNOPSIS
    Generates projects/boutique-microservices/.env with cryptographically
    strong secrets for local development.

.DESCRIPTION
    Every credential in this project now comes from .env, and the services
    refuse to start on missing or placeholder values. This script fills them
    in so you do not have to run openssl by hand on Windows.

    Secrets are generated with RandomNumberGenerator (the OS CSPRNG),
    NOT Get-Random, which is not cryptographically secure.

.EXAMPLE
    ./scripts/setup-local-env.ps1
    ./scripts/setup-local-env.ps1 -Force    # overwrite an existing .env
#>

[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot 'projects\boutique-microservices\.env'

if ((Test-Path $envPath) -and -not $Force) {
    Write-Host ""
    Write-Host "  .env already exists at:" -ForegroundColor Yellow
    Write-Host "    $envPath"
    Write-Host ""
    Write-Host "  Re-run with -Force to regenerate it." -ForegroundColor Yellow
    Write-Host "  (Regenerating the JWT secrets invalidates existing sessions.)"
    Write-Host ""
    exit 0
}

function New-Secret {
    param([int]$Bytes = 48)
    $buffer = [byte[]]::new($Bytes)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($buffer) } finally { $rng.Dispose() }
    # Strip characters that are awkward inside connection strings / shell quoting.
    return [Convert]::ToBase64String($buffer) -replace '[+/=]', ''
}

$postgresPassword = New-Secret 32
$accessSecret     = New-Secret 48
$refreshSecret    = New-Secret 48
$grafanaPassword  = New-Secret 18

# Guard against the (astronomically unlikely) case of identical secrets, since
# the services reject that configuration outright.
while ($accessSecret -eq $refreshSecret) { $refreshSecret = New-Secret 48 }

$content = @"
# =============================================================================
# Generated by scripts/setup-local-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
#
# LOCAL DEVELOPMENT ONLY. This file is gitignored — never commit it.
# Regenerate at any time with: ./scripts/setup-local-env.ps1 -Force
# =============================================================================

# --- Database ---------------------------------------------------------------
POSTGRES_USER=boutique_app
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=postgres
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

# --- JWT --------------------------------------------------------------------
# These MUST differ from each other; services refuse to start otherwise.
JWT_ACCESS_SECRET=$accessSecret
JWT_REFRESH_SECRET=$refreshSecret
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=7d
JWT_ISSUER=boutique-auth
JWT_AUDIENCE=boutique-api

# --- Application ------------------------------------------------------------
NODE_ENV=development
CORS_ALLOWED_ORIGINS=http://localhost:3000

# Local dev is plain HTTP, so the Secure cookie flag must stay off or the
# browser will silently refuse to store the refresh cookie.
COOKIE_SECURE=false
COOKIE_SAMESITE=lax

BCRYPT_ROUNDS=12

# --- Rate limiting ----------------------------------------------------------
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
AUTH_RATE_LIMIT_MAX=5

# --- Service discovery ------------------------------------------------------
AUTH_SERVICE_URL=http://auth:3002
PRODUCTS_SERVICE_URL=http://product-service:3003
ORDER_SERVICE_URL=http://order-service:3004
ORDERS_SERVICE_URL=http://orders:3005
USERS_SERVICE_URL=http://user-service:3006

# --- Observability ----------------------------------------------------------
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafanaPassword

# --- Frontend (build-time; never put a secret in a REACT_APP_* variable) -----
REACT_APP_API_URL=/api
"@

$dir = Split-Path -Parent $envPath
if (-not (Test-Path $dir)) { throw "Expected directory not found: $dir" }

# UTF-8 without BOM — a BOM would become part of the first variable's name.
[System.IO.File]::WriteAllText($envPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host ""
Write-Host "  Created .env with freshly generated secrets." -ForegroundColor Green
Write-Host "    $envPath"
Write-Host ""
Write-Host "  Grafana login:  admin / $grafanaPassword" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Next:" -ForegroundColor Yellow
Write-Host "    cd projects/boutique-microservices"
Write-Host "    docker compose up -d --build"
Write-Host ""
